const ITA_EXAM = new Date('2026-08-25T08:10:00+02:00');
const MATH_EXAM = new Date('2026-08-26T08:10:00+02:00');
const days=[
 {d:'19 AGO',title:'Occhio alle scomposizioni',math:'Fattor comune · trinomi · prodotti notevoli',ita:'Narratologia · analisi logica',mins:195,type:'study'},
 {d:'20 AGO',title:'Ruffini senza paura',math:'Divisione · Ruffini · teorema del resto',ita:'Verbi · ortografia',mins:190,type:'study'},
 {d:'21 AGO',title:'Frazioni ed equazioni',math:'C.E. · frazioni algebriche · equazioni',ita:'Analisi del testo narrativo',mins:205,type:'study'},
 {d:'22 AGO',title:'Segni e figure',math:'Disequazioni · triangoli · congruenza',ita:'Analisi logica · scrittura',mins:190,type:'study'},
 {d:'23 AGO',title:'Doppia simulazione',math:'Simulazione completa · correzione',ita:'Simulazione completa · correzione',mins:250,type:'study'},
 {d:'24 AGO',title:'Vigilia: Italiano al centro',math:'Formule e 6 esercizi lampo',ita:'Ripasso finale · scaletta · grammatica',mins:135,type:'study'},
 {d:'25 AGO',title:'Prova di Italiano',math:'Ripasso leggero dopo la prova',ita:'ESAME · 08:10–09:40',mins:90,type:'exam-ita'},
 {d:'26 AGO',title:'Prova di Matematica',math:'ESAME · 08:10–10:30',ita:'Completato',mins:140,type:'exam-math'}
];
const dayPlans=[
 {goal:'Riconoscere il metodo di scomposizione senza procedere per tentativi.',blocks:[
  ['∑','Matematica · teoria','20 min','Apri le schede 1 “Scomposizioni” e 2 “Ruffini”. Ripeti ad alta voce la checklist dei metodi.','math'],
  ['✎','Matematica · allenamento','75 min','Svolgi gli esercizi 1–4: fattore comune, trinomio speciale, scomposizione mista e Ruffini. Usa il primo hint solo dopo un tentativo scritto.','math'],
  ['¶','Italiano · teoria','20 min','Apri le schede “Analisi narrativa” e “Analisi logica”. Memorizza le domande-guida.','ita'],
  ['✎','Italiano · allenamento','50 min','Svolgi i primi 2 esercizi di analisi logica e l’esercizio di narratologia.','ita'],
  ['◆','Verifica finale','20 min','Completa il quiz di Matematica. Obiettivo minimo: 4/5. Annota un errore da non ripetere.','quiz']
 ]},
 {goal:'Usare Ruffini con coefficienti completi e controllare il resto.',blocks:[
  ['∑','Matematica · teoria','20 min','Ripassa Ruffini, teorema del resto e presenza dei coefficienti zero.','math'],
  ['✎','Matematica · allenamento','85 min','Rifai l’esercizio 4 senza hint; poi svolgi gli esercizi 5 e 6 sulle frazioni come consolidamento.','math'],
  ['¶','Italiano · grammatica','55 min','Studia le schede Verbi e Ortografia; svolgi i relativi esercizi.','ita'],
  ['◆','Verifica finale','20 min','Quiz Italiano, obiettivo 4/5.','quiz']
 ]},
 {goal:'Scrivere sempre le condizioni di esistenza prima dei calcoli.',blocks:[
  ['∑','Frazioni algebriche','75 min','Scheda 3; esercizi 5 e 6 con C.E., scomposizione e denominatore comune.','math'],
  ['∑','Equazioni','55 min','Scheda 4; esercizi 7 e 8, controllando la soluzione nelle C.E.','math'],
  ['¶','Analisi del testo','55 min','Scheda Analisi narrativa; esercizi Narratologia e Analisi del testo.','ita'],
  ['◆','Quiz misto','20 min','Quiz Matematica e correzione degli errori.','quiz']
 ]},
 {goal:'Controllare versi, ipotesi e motivazioni.',blocks:[
  ['∑','Disequazioni','50 min','Scheda 5 ed esercizio 9; rappresenta il risultato su una retta.','math'],
  ['△','Geometria','60 min','Scheda 6 ed esercizio 10; scrivi ipotesi, tesi e teorema usato.','math'],
  ['¶','Analisi logica e scrittura','60 min','Esercizi 1–2 e scaletta dell’esercizio di scrittura.','ita'],
  ['◆','Verifica finale','20 min','Quiz Italiano e diario degli errori.','quiz']
 ]},
 {goal:'Lavorare con il tempo reale e individuare gli ultimi punti deboli.',blocks:[
  ['⏱','Simulazione Matematica A','120 min','Svolgi la prova senza aiuti. Correggi solo dopo la consegna.','exam'],
  ['☕','Pausa vera','30 min','Allontanati dallo schermo, mangia e bevi.',''],
  ['⏱','Simulazione Italiano','90 min','Svolgi la prova completa con revisione finale.','exam'],
  ['◎','Diario errori','20 min','Dividi gli errori in metodo, calcolo/forma e distrazione.','progress']
 ]},
 {goal:'Consolidare Italiano senza arrivare stanchi alla prova.',blocks:[
  ['¶','Ripasso Italiano','45 min','Rivedi analisi narrativa, logica, verbi e ortografia. Niente nuovi argomenti.','ita'],
  ['✎','Esercizio finale','45 min','Svolgi Analisi del testo e rileggi con la checklist P.E.E.','ita'],
  ['∑','Matematica leggera','30 min','Rileggi formule e rifai due esercizi già corretti.','math'],
  ['☾','Preparazione','15 min','Prepara materiale e sveglia. Termina lo studio in anticipo.','']
 ]},
 {goal:'Italiano 08:10–09:40. Leggere tutto, gestire il tempo, rileggere.',blocks:[
  ['¶','Prova di Italiano','90 min','Presentati in anticipo. Lascia gli ultimi 10 minuti alla revisione.','exam'],
  ['∑','Dopo la prova','45 min','Pausa lunga; poi solo formule e due esercizi sicuri di Matematica.','math'],
  ['☾','Riposo','—','Nessuna simulazione completa. Prepara il materiale e dormi.','']
 ]},
 {goal:'Matematica 08:10–10:30. Scrivere tutti i passaggi e le C.E.',blocks:[
  ['∑','Prova di Matematica','140 min','Leggi tutti i quesiti, parti dai sicuri e tieni 15 minuti per il controllo.','exam']
 ]}
];
const topics={
 math:[
  ['Scomposizioni','Checklist: fattore comune; raccoglimento parziale; prodotti notevoli; trinomio speciale; Ruffini. Una scomposizione è completa quando ogni fattore non si può più scomporre.','x²+7x+10=(x+5)(x+2): cerco due numeri con prodotto 10 e somma 7.'],
  ['Ruffini','Per P(x):(x−a), usa a. Scrivi tutti i coefficienti, anche gli zeri. Il resto è P(a); se vale 0, x−a è un fattore.','x³−4x²+x+6 con a=2 dà quoziente x²−2x−3 e resto 0.'],
  ['Frazioni algebriche','Prima le C.E.: annulla ogni denominatore e vieta quei valori. Poi scomponi, semplifica solo fattori e usa il m.c.m. per sommare.','(x²−9)/(x²−3x), C.E. x≠0,3; diventa (x+3)/x con le C.E. originali.'],
  ['Equazioni','Togli parentesi, elimina denominatori, porta le x a sinistra e i numeri a destra. Nelle fratte: C.E. prima, verifica alla fine.','(x−1)/x=2, x≠0 → x−1=2x → x=−1, accettabile.'],
  ['Disequazioni','Procedi come nelle equazioni, ma inverti il verso quando moltiplichi o dividi per un numero negativo. Rappresenta la soluzione sulla retta.','−2x>6 → x<−3. Il verso cambia dividendo per −2.'],
  ['Geometria','Scrivi sempre: ipotesi, tesi, costruzione, dimostrazione. Cita il criterio o teorema usato; non affidarti al disegno.','Nei triangoli: LAL, ALA e LLL. In un isoscele gli angoli alla base sono congruenti.']
 ],
 ita:[
  ['Analisi narrativa','Individua sequenze, fabula/intreccio, tempo, spazio, sistema dei personaggi, narratore e focalizzazione. Ogni risposta va provata con un elemento del testo.','“Io non dimenticherò…” indica narratore interno e prima persona.'],
  ['Analisi epica','Riconosci invocazione, proemio, epiteti, similitudini e intervento divino. Collega l’episodio ai valori dell’eroe e al conflitto.','Achille incarna onore e ira; Odisseo intelligenza e desiderio del ritorno.'],
  ['Analisi logica','Trova prima il predicato, poi chi compie/subisce l’azione. Distingui predicato verbale e nominale; completa con attributi, apposizioni e complementi.','“Il giovane Ulisse raccontò la storia ai Feaci”: soggetto Ulisse; PV raccontò; oggetto la storia; termine ai Feaci.'],
  ['Verbi','Analizza coniugazione, modo, tempo, persona, numero, forma e funzione. Osserva ausiliare e participio nei tempi composti.','“sarebbero partiti”: partire, indicativo? No: condizionale passato, 3ª plurale, forma attiva.'],
  ['Ortografia','Controlla accenti, apostrofi, h, doppie, maiuscole e punteggiatura. Rileggi una volta solo per la forma.','“Qual è” senza apostrofo; “un’amica” con apostrofo; “po’” con apostrofo.'],
  ['Scrittura','Prima scaletta: tesi/idea centrale, 2–3 nuclei, conclusione. Usa connettivi, paragrafi e citazioni brevi dal testo; poi revisione.','Risposta P.E.E.: punto, evidenza dal testo, spiegazione del collegamento.']
 ]
};
const exercises={
 math:[
  {t:'Scomponi completamente',q:'6x² + 15x',level:'BASE',h:['Cerca il massimo fattore comune tra 6 e 15 e tra x² e x.','Il MCD è 3 e la potenza minima è x.'],s:'6x²+15x = 3x(2x+5). Controllo: 3x·2x=6x² e 3x·5=15x.'},
  {t:'Riconosci il metodo',q:'x² + 7x + 10',level:'BASE',h:['Servono due numeri: prodotto 10, somma 7.','Prova 5 e 2.'],s:'x²+7x+10=(x+5)(x+2).'},
  {t:'Scomposizione mista',q:'2x³ − 8x',level:'MEDIO',h:['Prima raccogli 2x.','Dentro resta una differenza di quadrati.'],s:'2x(x²−4)=2x(x−2)(x+2).'},
  {t:'Ruffini',q:'Scomponi x³ − 4x² + x + 6 sapendo che 2 è una radice.',level:'MEDIO',h:['Usa i coefficienti 1, −4, 1, 6.','Con Ruffini ottieni 1, −2, −3 e resto 0.'],s:'P(x)=(x−2)(x²−2x−3)=(x−2)(x−3)(x+1).'},
  {t:'Frazione algebrica',q:'Semplifica (x²−9)/(x²−3x) indicando le C.E.',level:'MEDIO',h:['Le C.E. vengono dal denominatore originale.','Scomponi: x²−9 e x²−3x.'],s:'C.E. x≠0,3. [(x−3)(x+3)]/[x(x−3)] = (x+3)/x.'},
  {t:'Somma di frazioni',q:'Calcola 2/x + 1/(x+1) e indica le C.E.',level:'AVANZATO',h:['C.E.: x≠0 e x≠−1.','Denominatore comune x(x+1).'],s:'[2(x+1)+x]/[x(x+1)] = (3x+2)/[x(x+1)], con x≠0,−1.'},
  {t:'Equazione intera',q:'3(2x−1)−2(x+4)=5',level:'BASE',h:['Svolgi prima le parentesi.','6x−3−2x−8=5.'],s:'4x−11=5 → 4x=16 → x=4.'},
  {t:'Equazione fratta',q:'(x−1)/x = 2',level:'MEDIO',h:['Prima scrivi x≠0.','Moltiplica entrambi i membri per x.'],s:'C.E. x≠0. x−1=2x → x=−1, che rispetta la C.E.'},
  {t:'Disequazione',q:'5−2x ≥ 11',level:'BASE',h:['Sottrai 5 da entrambi i membri.','Quando dividi per −2 devi cambiare verso.'],s:'−2x≥6 → x≤−3.'},
  {t:'Geometria',q:'In un triangolo isoscele ABC con AB=AC, l’angolo al vertice A misura 44°. Calcola gli angoli alla base.',level:'MEDIO',h:['Gli angoli alla base sono congruenti.','La somma degli angoli interni è 180°.'],s:'B=C=(180°−44°)/2=68°.'},
  {t:'Problema · numeri consecutivi',q:'La somma di tre numeri interi consecutivi è 72. Trova i tre numeri.',level:'PROBLEMA',h:['Chiama x il numero centrale. Gli altri sono x−1 e x+1.','Scrivi (x−1)+x+(x+1)=72.'],s:'Scelgo x come numero centrale. (x−1)+x+(x+1)=72 → 3x=72 → x=24. I numeri sono 23, 24 e 25. Controllo: 23+24+25=72.'},
  {t:'Problema · età',q:'Luca ha 5 anni più di Sara. Fra 3 anni la somma delle loro età sarà 35. Quanti anni hanno oggi?',level:'PROBLEMA',h:['Poni oggi Sara=x e Luca=x+5.','Fra 3 anni avranno x+3 e x+8.'],s:'Sara=x, Luca=x+5. Fra 3 anni: (x+3)+(x+8)=35 → 2x+11=35 → x=12. Sara ha 12 anni e Luca 17. Controllo futuro: 15+20=35.'},
  {t:'Problema · rettangolo',q:'La base di un rettangolo è 4 cm più del doppio dell’altezza. Il perimetro è 44 cm. Calcola le dimensioni.',level:'PROBLEMA',h:['Poni altezza=x; allora base=2x+4.','Usa 2(base+altezza)=44.'],s:'h=x, b=2x+4. 2[(2x+4)+x]=44 → 6x+8=44 → x=6. Altezza 6 cm, base 16 cm. Controllo: 2(6+16)=44 cm.'},
  {t:'Problema · sconto',q:'Dopo uno sconto del 20%, uno zaino costa 48 €. Qual era il prezzo iniziale?',level:'PROBLEMA',h:['Dopo lo sconto resta l’80% del prezzo.','Poni 0,8x=48.'],s:'Prezzo iniziale=x. Pagato l’80%: 0,8x=48 → x=48/0,8=60 €. Controllo: il 20% di 60 è 12; 60−12=48.'},
  {t:'Problema · frazione',q:'I 3/5 degli studenti di una classe sono 18. Quanti studenti ci sono in tutto?',level:'PROBLEMA',h:['Poni x il totale.','Scrivi (3/5)x=18.'],s:'(3/5)x=18 → x=18·5/3=30. La classe ha 30 studenti. Controllo: 3/5 di 30 = 18.'},
  {t:'Problema · moto uniforme',q:'Due ciclisti partono nello stesso momento da luoghi distanti 54 km e vanno uno verso l’altro a 12 km/h e 15 km/h. Dopo quanto tempo si incontrano?',level:'PROBLEMA',h:['Insieme riducono la distanza di 12+15 km ogni ora.','Scrivi 12t+15t=54.'],s:'12t+15t=54 → 27t=54 → t=2 ore. Controllo: percorrono 24 km e 30 km; totale 54 km.'},
  {t:'Problema · miscela di monete',q:'In un salvadanaio ci sono monete da 1 € e da 2 €, in tutto 18 monete per 27 €. Quante sono per tipo?',level:'PROBLEMA',h:['Poni x le monete da 2 €. Quelle da 1 € sono 18−x.','Valore totale: 2x+(18−x)=27.'],s:'2x+(18−x)=27 → x+18=27 → x=9. Ci sono 9 monete da 2 € e 9 da 1 €. Controllo: 18+9=27 €.'},
  {t:'Problema · geometria ed equazione',q:'In un triangolo un angolo è il doppio di un altro; il terzo misura 30°. Trova i due angoli incogniti.',level:'PROBLEMA',h:['Poni l’angolo minore=x e l’altro=2x.','La somma interna è 180°.'],s:'x+2x+30°=180° → 3x=150° → x=50°. Gli angoli sono 50°, 100° e 30°. Controllo: somma 180°.'}
 ],
 ita:[
  {t:'Analisi logica',q:'Il giovane Ulisse raccontò una storia straordinaria ai Feaci.',level:'BASE',h:['Trova prima il verbo: raccontò.','Chiedi: chi? che cosa? a chi?'],s:'Soggetto: Ulisse; attributo del soggetto: giovane; predicato verbale: raccontò; complemento oggetto: una storia; attributo dell’oggetto: straordinaria; complemento di termine: ai Feaci.'},
  {t:'Analisi logica',q:'La nave degli Achei fu distrutta dalla tempesta durante la notte.',level:'MEDIO',h:['“fu distrutta” è una forma passiva.','Chi compie l’azione nella frase passiva?'],s:'Soggetto: la nave; specificazione: degli Achei; predicato verbale passivo: fu distrutta; causa efficiente: dalla tempesta; tempo determinato: durante la notte.'},
  {t:'Verbi',q:'Analizza: “Se avessero ascoltato, sarebbero tornati prima.”',level:'MEDIO',h:['Sono due tempi composti.','Il primo introduce una condizione non realizzata.'],s:'avessero ascoltato: ascoltare, congiuntivo trapassato, 3ª plurale, attiva. sarebbero tornati: tornare, condizionale passato, 3ª plurale, attiva.'},
  {t:'Ortografia',q:'Correggi: Qual’è l’obbiettivo? Un pò di attenzione non fà male.',level:'BASE',h:['Qual è non vuole apostrofo.','“po’” è un troncamento; “fa” qui non è accentato.'],s:'Qual è l’obiettivo? Un po’ di attenzione non fa male.'},
  {t:'Narratologia',q:'Un narratore dice: “Solo anni dopo capii perché mio padre era partito”. Indica tipo di narratore, rapporto fabula/intreccio e focalizzazione più probabile.',level:'MEDIO',h:['Il narratore parla di sé in prima persona.','“Anni dopo” segnala un ritorno su eventi passati.'],s:'Narratore interno/autodiegetico; intreccio con analessi (racconto retrospettivo); focalizzazione interna, limitata alla coscienza del narratore.'},
  {t:'Epica',q:'Spiega in 5–7 righe che cosa distingue l’eroismo di Achille da quello di Odisseo.',level:'AVANZATO',h:['Confronta forza/onore con intelligenza/ritorno.','Cita un episodio o un tratto per ciascuno.'],s:'Risposta attesa: Achille ricerca onore e gloria guerriera e agisce secondo l’ira e il codice aristocratico; Odisseo vince soprattutto con intelligenza, parola e capacità di adattarsi. Il primo è l’eroe della forza e della fama, il secondo del viaggio e del ritorno. Sono entrambi coraggiosi, ma affrontano gli ostacoli con qualità diverse.'},
  {t:'Analisi del testo',q:'Scrivi una risposta P.E.E. alla domanda: “Come viene costruita la tensione in una scena notturna?”',level:'AVANZATO',h:['Punto: formula una tesi chiara. Evidenza: cita un dettaglio. Spiegazione: chiarisci l’effetto.','Puoi usare buio, silenzio, frasi brevi, attesa o focalizzazione limitata.'],s:'Esempio: La tensione nasce dalla percezione incompleta del personaggio. Il testo insiste sul silenzio e su rumori non identificati, mentre le frasi diventano brevi. Questi dettagli limitano le informazioni del lettore e trasformano l’attesa in paura.'},
  {t:'Scrittura',q:'Prepara una scaletta per un testo di 15 righe: “Un errore che mi ha insegnato qualcosa”.',level:'BASE',h:['Introduzione breve, episodio centrale, riflessione finale.','Scegli un solo episodio concreto.'],s:'Scaletta possibile: 1) situazione iniziale e obiettivo; 2) errore e conseguenza; 3) reazione immediata; 4) aiuto o nuova comprensione; 5) che cosa è cambiato nel comportamento; 6) conclusione collegata al presente.'}
 ]
};
exercises.math.push(
 {t:'Ruffini · divisore con segno positivo',q:'Dividi P(x)=x³+2x²−5x−6 per x+1. Stabilisci se x+1 è un fattore e, se possibile, scomponi completamente.',level:'MEDIO',h:['Per x+1 devi usare a=−1. Coefficienti: 1, 2, −5, −6.','Ruffini produce 1, 1, −6 e resto 0; il quoziente è x²+x−6.'],s:'Uso −1: abbasso 1; 1·(−1)=−1 e 2−1=1; 1·(−1)=−1 e −5−1=−6; −6·(−1)=6 e −6+6=0. Quindi x+1 è un fattore. Il quoziente x²+x−6=(x+3)(x−2). Risultato: (x+1)(x+3)(x−2).'},
 {t:'Ruffini · termine mancante',q:'Dividi P(x)=2x³−5x+3 per x−1 e indica quoziente e resto.',level:'MEDIO',h:['Manca x²: devi scrivere i coefficienti 2, 0, −5, 3.','Con a=1 ottieni 2, 2, −3 e resto 0.'],s:'Coefficienti 2,0,−5,3. Abbasso 2; 2·1=2, 0+2=2; 2·1=2, −5+2=−3; −3·1=−3, 3−3=0. Quoziente 2x²+2x−3, resto 0. Dunque P(x)=(x−1)(2x²+2x−3).'},
 {t:'Ruffini · ricerca della radice',q:'Scomponi P(x)=x³−2x²−5x+6. Non viene fornita la radice: cercala tra i divisori del termine noto.',level:'AVANZATO',h:['Le possibili radici intere sono ±1, ±2, ±3, ±6. Prova prima i valori più piccoli.','P(1)=0. Ruffini con 1 dà x²−x−6.'],s:'Provo i divisori di 6: P(1)=1−2−5+6=0, quindi x−1 è fattore. Ruffini sui coefficienti 1,−2,−5,6 dà quoziente x²−x−6. Scompongo il quoziente: (x−3)(x+2). Risultato: P(x)=(x−1)(x−3)(x+2).'},
 {t:'Frazioni · espressione completa',q:'Calcola 3/(x−2) − 1/(x+2) e indica tutte le C.E.',level:'MEDIO',h:['C.E. x≠2 e x≠−2. Il denominatore comune è (x−2)(x+2).','Il numeratore diventa 3(x+2)−(x−2).'],s:'C.E. x≠±2. [3(x+2)−(x−2)]/[(x−2)(x+2)] = (3x+6−x+2)/(x²−4) = (2x+8)/(x²−4)=2(x+4)/(x²−4). Non ci sono fattori comuni da semplificare.'},
 {t:'Equazione · caso indeterminato o impossibile',q:'Classifica e risolvi: 3(2x−1)−6x = −3.',level:'MEDIO',h:['Sviluppa il primo membro.','Ottieni −3=−3: che cosa significa?'],s:'3(2x−1)−6x=6x−3−6x=−3. L’equazione diventa −3=−3, sempre vera. È indeterminata: ogni numero reale è soluzione.'},
 {t:'Disequazione · parentesi e segni',q:'Risolvi 4−3(2x−1) ≤ 2(x+5) e rappresenta la soluzione.',level:'MEDIO',h:['Sviluppa: 4−6x+3 ≤ 2x+10.','Porta le x a sinistra: −8x≤3; dividendo per −8 cambia il verso.'],s:'7−6x≤2x+10 → −8x≤3 → x≥−3/8. Sulla retta: punto pieno in −3/8 e semiretta verso destra.'},
 {t:'Geometria · congruenza',q:'Nel triangolo ABC, M è il punto medio di BC. Sapendo che AB=AC, dimostra che i triangoli ABM e ACM sono congruenti e deduci che AM è bisettrice di A.',level:'AVANZATO',h:['Scrivi tre coppie di lati congruenti.','AB=AC; BM=CM perché M è punto medio; AM è comune. Usa LLL.'],s:'Ipotesi: AB=AC e BM=CM. Inoltre AM=AM perché lato comune. Quindi i triangoli ABM e ACM sono congruenti per LLL. Gli angoli corrispondenti BÂM e MÂC sono congruenti; per definizione AM è bisettrice dell’angolo A.'}
);
exercises.ita.push(
 {t:'Testo narrativo · Il corridoio',q:`Leggi il brano e rispondi in modo completo.

Quando il custode spense le luci del piano terra, Elia era ancora nell’aula di musica. Aveva promesso di riportare il vecchio metronomo nell’armadio, ma la chiave non girava. Dal corridoio arrivò un colpo secco, poi un fruscio. Elia trattenne il respiro. Pensò al gatto che talvolta entrava dalla finestra della palestra, eppure quel rumore sembrava troppo regolare: tre colpi, una pausa, altri tre colpi. Aprì la porta. Il corridoio era vuoto, illuminato soltanto dalla spia verde dell’uscita. Fece due passi e il suono ricominciò. Questa volta capì. Dietro la porta del laboratorio, il professor Neri batteva con una riga sul vetro: la maniglia si era bloccata. Elia corse a chiamare il custode. Solo più tardi, tornando a casa, rise della paura che gli aveva fatto immaginare presenze misteriose.

Domande: 1) Dividi il testo in almeno quattro sequenze e indica il tipo. 2) Il narratore è interno o esterno? 3) Qual è la focalizzazione? Porta una prova. 4) Individua il momento di massima tensione e spiega come viene costruito. 5) Riassumi in 60–80 parole.`,level:'TESTO COMPLETO',h:['Per le sequenze osserva: situazione iniziale, rumori, esplorazione, scoperta, conclusione.','La voce è in terza persona, ma il lettore conosce soprattutto percezioni e pensieri di Elia.'],s:`1) Possibile divisione: situazione iniziale narrativa; rumori e paura narrativa/riflessiva; esplorazione descrittiva e narrativa; scoperta narrativa; conclusione riflessiva. 2) Narratore esterno. 3) Focalizzazione interna su Elia: leggiamo ciò che sente e immagina, ma non sappiamo subito chi produce i colpi. 4) Il culmine è quando Elia apre la porta e avanza nel corridoio; buio, silenzio, suoni ripetuti, frasi brevi e informazioni limitate creano attesa. 5) Il riassunto deve conservare promessa, rumori, ricerca, scoperta del professore e riflessione finale, senza commenti personali.`},
 {t:'Testo narrativo · La fotografia',q:`Leggi il brano.

Marta trovò la fotografia mentre svuotava la scrivania della nonna. Era piegata in quattro e mostrava una ragazza davanti a una bicicletta rossa. Sul retro, una data: 3 maggio 1968. Marta portò la foto in cucina. La nonna la osservò a lungo, poi sorrise. «Quel giorno disobbedii a mio padre», disse. Raccontò che aveva preso la bicicletta per raggiungere il paese vicino e sostenere un esame di ammissione. Il padre riteneva inutile che una ragazza continuasse a studiare; lei, invece, aveva preparato l’esame di nascosto. Quando tornò, trovò suo padre sulla soglia. Non gridò. Guardò la busta con il risultato, lesse la parola “ammessa” e si limitò a spostarsi per lasciarla entrare. Marta rigirò la fotografia tra le dita. Fino a quel momento aveva conosciuto la nonna come una donna prudente; ora vedeva, dietro i suoi gesti misurati, il coraggio di quella corsa.

Domande: 1) Ricostruisci fabula e intreccio. 2) Individua l’analessi. 3) Descrivi la trasformazione dello sguardo di Marta. 4) Spiega il valore simbolico della bicicletta. 5) Trova due forme verbali e analizzale completamente.`,level:'TESTO COMPLETO',h:['L’ordine del racconto parte dal presente e torna al 1968.','La bicicletta non è solo un mezzo di trasporto: rende possibile una scelta autonoma.'],s:`1) Fabula: preparazione segreta, viaggio, esame, ritorno, reazione del padre, molti anni dopo ritrovamento della foto. Intreccio: presente → racconto retrospettivo → ritorno al presente. 2) L’intero racconto della nonna è un’analessi. 3) Marta passa dall’immagine di una nonna soltanto prudente alla scoperta del suo coraggio. 4) La bicicletta simboleggia autonomia, movimento e accesso allo studio. 5) Esempi: “aveva preparato”, indicativo trapassato prossimo, 3ª singolare, attiva; “continuasse”, congiuntivo imperfetto, 3ª singolare, attiva.`},
 {t:'Epica · La scelta dell’eroe',q:`Leggi questo brano originale di argomento epico.

Quando l’alba dalle dita rosate comparve sopra il mare, Aristeo vide le vele nere avvicinarsi alla costa. I compagni gli chiesero di chiudere le porte e attendere rinforzi, ma dalla pianura giungevano ancora i pastori con le greggi. «Se chiudiamo ora», disse, «salveremo le mura e perderemo il nostro popolo». Affidò allora il comando della torre al vecchio Meone e scese con dodici uomini verso il guado. Non cercava una vittoria impossibile: voleva guadagnare il tempo necessario perché gli ultimi abitanti raggiungessero la città. Prima dello scontro posò la mano sulla terra e invocò Atena, signora del consiglio. Poi ordinò ai compagni di arretrare lentamente, senza spezzare la formazione. Quando infine le porte si chiusero alle loro spalle, Aristeo aveva perduto lo scudo, ma nessun pastore era rimasto fuori.

Domande: 1) Individua due caratteristiche dello stile epico. 2) Quale modello di eroismo rappresenta Aristeo? 3) Che funzione ha l’invocazione ad Atena? 4) Confronta Aristeo con Achille o Odisseo in 8–10 righe.`,level:'TESTO EPICO',h:['Cerca formula dell’alba, epiteto della dea, discorso diretto e azione collettiva.','Aristeo non cerca gloria personale: valuta conseguenze e protegge la comunità.'],s:`1) Formula “alba dalle dita rosate”, epiteto “signora del consiglio”, discorso solenne e impresa in difesa del popolo. 2) Eroismo responsabile e comunitario: rischia per salvare gli altri e usa strategia. 3) L’invocazione collega l’azione umana al mondo divino e caratterizza la scelta come guidata dalla sapienza. 4) Con Odisseo condivide prudenza e strategia; con Achille coraggio e disponibilità allo scontro. Si distingue dalla ricerca di gloria individuale perché mette al centro la salvezza della comunità.`},
 {t:'Epica · Odisseo e il nome',q:`Leggi il brano originale ispirato ai temi dell’Odissea.

Lo straniero sedeva accanto al fuoco senza rivelare il proprio nome. Il re gli offrì pane, vino e un mantello asciutto; soltanto dopo il pasto gli domandò da quale terra provenisse. Per molte notti l’ospite aveva imparato a diffidare delle domande, ma quella casa rispettava la legge sacra dell’accoglienza. «Ho avuto molti nomi», rispose, «alcuni scelti per ingannare i nemici, altri pronunciati dagli amici che non rivedrò. Il mio vero nome appartiene all’isola verso cui navigo». Il re non insistette. Ordinò che all’alba una nave fosse preparata. Lo straniero comprese allora che poteva raccontare la propria storia senza perdere la libertà.

Domande: 1) Quale valore epico è centrale? 2) Perché il nome è collegato all’identità? 3) Spiega la focalizzazione. 4) Collega il testo a due temi dell’Odissea. 5) Scrivi un titolo motivato.`,level:'TESTO EPICO',h:['La legge dell’ospitalità in greco è detta xenia.','Pensa ai temi del ritorno, dell’identità nascosta, del racconto e dell’astuzia.'],s:`1) È centrale la xenia, l’ospitalità sacra: prima si accoglie e si nutre, poi si interroga. 2) Il nome conserva origine, relazioni e meta; rivelarlo significa recuperare la propria storia. 3) Narratore esterno con focalizzazione interna sullo straniero, di cui conosciamo diffidenza e comprensione finale. 4) Ritorno alla patria, identità celata, racconto delle avventure e prudenza. 5) Esempio: “Il nome e la casa”, perché unisce il problema dell’identità alla meta del viaggio.`},
 {t:'Analisi logica · periodo articolato',q:'Analizza logicamente: “Durante la tempesta, il vecchio capitano della nave affidò con calma il timone al giovane marinaio.”',level:'MEDIO',h:['Predicato: affidò. Chi affidò? Che cosa? A chi?','“Durante la tempesta” indica tempo; “con calma” modo.'],s:'Complemento di tempo determinato: durante la tempesta; soggetto: il capitano; attributo: vecchio; specificazione: della nave; predicato verbale: affidò; modo: con calma; complemento oggetto: il timone; termine: al marinaio; attributo del termine: giovane.'},
 {t:'Verbi · analisi nel contesto',q:'Nel periodo “Quando ebbe terminato il racconto, Elena si accorse che gli amici l’avevano ascoltata in silenzio”, analizza tutte le forme verbali.',level:'MEDIO',h:['Ci sono tre forme: ebbe terminato, si accorse, avevano ascoltata.','Distingui trapassato remoto, passato remoto e trapassato prossimo.'],s:'“ebbe terminato”: terminare, indicativo trapassato remoto, 3ª singolare, attiva; “si accorse”: accorgersi, indicativo passato remoto, 3ª singolare, forma pronominale; “avevano ascoltata”: ascoltare, indicativo trapassato prossimo, 3ª plurale, attiva. Il participio è accordato con il pronome oggetto femminile “l’”.'},
 {t:'Ortografia · revisione di un paragrafo',q:'Correggi e riscrivi: “Un pò più tardi Marco a deciso di andare via, ma non sapeva qual’era la strada giusta. Gli amici gli anno detto che cè n’era una più breve.”',level:'MEDIO',h:['Controlla po’, ha/a, qual era, hanno/anno, c’è.','Attenzione: “qual era” non prende apostrofo.'],s:'“Un po’ più tardi Marco ha deciso di andare via, ma non sapeva qual era la strada giusta. Gli amici gli hanno detto che ce n’era una più breve.” Correzioni: po’ troncamento; ha/hanno forme di avere; qual era senza apostrofo; ce n’era con particella “ce” e verbo essere.'},
 {t:'Scrittura · risposta argomentata',q:'Scrivi 12–15 righe: “Il coraggio consiste sempre nell’affrontare un pericolo?” Usa una tesi, due argomenti, un esempio tratto da un testo studiato e una conclusione.',level:'SCRITTURA',h:['Puoi sostenere che esistono anche coraggio morale e responsabilità.','Struttura: tesi → argomento 1 → esempio → argomento 2 → conclusione.'],s:'Criteri di correzione: tesi esplicita; due argomenti distinti; esempio pertinente (per esempio Ettore, Achille, Odisseo o un personaggio narrativo); connettivi; conclusione coerente; ortografia controllata. Possibile tesi: il coraggio non è soltanto affrontare un rischio fisico, ma anche assumersi responsabilità e difendere una scelta giusta.'}
);
const quizzes={math:[['Qual è il primo controllo in una scomposizione?',['Ruffini','Fattore comune','Formula risolutiva'],1],['Se P(3)=0, quale fattore possiede P(x)?',['x+3','3x','x−3'],2],['La C.E. di 1/(x−4) è:',['x≠4','x>4','x=4'],0],['Dividendo una disequazione per −3:',['Il verso resta','Il verso cambia','Si annulla tutto'],1],['Quale criterio usa due lati e l’angolo compreso?',['ALA','LLL','LAL'],2]],ita:[['Un narratore-personaggio è:',['Interno','Onnisciente sempre','Esterno'],0],['“fu premiato” è forma:',['Attiva','Passiva','Riflessiva'],1],['In “Marco è stanco”, il predicato è:',['Verbale','Nominale','Sottinteso'],1],['Quale forma è corretta?',["Qual'è","Qual è","Qualé"],1],['P.E.E. significa:',['Punto, evidenza, spiegazione','Premessa, esempio, epilogo','Personaggi, eventi, emozioni'],0]]};
const examSets={
 mathA:{title:'Matematica · Simulazione A',minutes:120,questions:[
  ['Calcolo letterale','Semplifica: (2x−3)² − (x+1)(x−1) + 2x(3−x).','Sviluppando: 4x²−12x+9 −x²+1 +6x−2x² = x²−6x+10.'],
  ['Scomposizioni','Scomponi completamente: 3x³−12x.','3x(x²−4)=3x(x−2)(x+2).'],
  ['Ruffini e teorema del resto','Verifica che 2 sia uno zero di P(x)=x³−3x²−4x+12 e scomponi P(x).','P(2)=8−12−8+12=0. Ruffini dà x²−x−6; quindi P(x)=(x−2)(x−3)(x+2).'],
  ['Frazioni algebriche','Indica le C.E. e semplifica: (x²−4)/(x²+x−2).','Denominatore=(x+2)(x−1), quindi x≠−2,1. La frazione diventa (x−2)/(x−1), mantenendo le C.E. originali.'],
  ['Equazione fratta','Risolvi: 2/(x−1) = 1 + 3/(x−1).','C.E. x≠1. Moltiplicando per x−1: 2=x−1+3=x+2, quindi x=0, accettabile.'],
  ['Disequazione','Risolvi e rappresenta sulla retta: 3−2(2x−1) > x+8.','3−4x+2>x+8 → −5x>3 → x<−3/5.'],
  ['Problema con equazione','La base di un rettangolo supera l’altezza di 5 cm. Il perimetro è 46 cm. Trova le dimensioni.','Posto h=x e b=x+5: 2[x+(x+5)]=46 → 4x+10=46 → x=9. Altezza 9 cm, base 14 cm.'],
  ['Geometria dimostrativa','Nel triangolo isoscele ABC, AB=AC. La bisettrice AD dell’angolo al vertice incontra BC in D. Dimostra che BD=DC. Scrivi ipotesi, tesi e criterio usato.','Nei triangoli ABD e ACD: AB=AC per ipotesi; AD è comune; BAD=DAC perché AD è bisettrice. I triangoli sono congruenti per LAL, dunque BD=DC.']
 ]},
 mathB:{title:'Matematica · Simulazione B',minutes:120,questions:[
  ['Polinomi e prodotti notevoli','Riduci: (3x+2)(3x−2) − 2x(x−5) − (x−1)².','9x²−4 −2x²+10x −x²+2x−1 = 6x²+12x−5.'],
  ['Scomposizioni miste','Scomponi completamente: 2x³+4x²−18x−36.','Raccoglimento parziale: 2x²(x+2)−18(x+2)=(x+2)(2x²−18)=2(x+2)(x−3)(x+3).'],
  ['Divisione e Ruffini','Dividi 2x³−3x²−11x+6 per x−3 e stabilisci se la divisione è esatta.','Ruffini con 3 sui coefficienti 2,−3,−11,6 dà quoziente 2x²+3x−2 e resto 0: divisione esatta.'],
  ['Operazioni con frazioni algebriche','Calcola 1/(x−2) + 2/(x+2), indicando le C.E.','C.E. x≠2,−2. Denominatore comune (x−2)(x+2); numeratore x+2+2x−4=3x−2. Risultato (3x−2)/(x²−4).'],
  ['Equazione intera','Risolvi: 4(2x−3)−3(x+2)=2(x−5)+7.','8x−12−3x−6=2x−10+7 → 5x−18=2x−3 → 3x=15 → x=5.'],
  ['Equazione fratta','Risolvi: (x+1)/(x−2)=3/2.','C.E. x≠2. 2(x+1)=3(x−2) → 2x+2=3x−6 → x=8, accettabile.'],
  ['Disequazione','Risolvi: (2x−1)/3 ≤ x+2.','2x−1≤3x+6 → −7≤x, cioè x≥−7.'],
  ['Geometria','Due rette parallele sono tagliate da una trasversale. Un angolo interno misura 67°. Determina gli angoli alterni interni e i coniugati interni, motivando.','Gli alterni interni sono congruenti, quindi misurano 67°. I coniugati interni sono supplementari: 180°−67°=113°.']
 ]}
};
const navItems=[['dashboard','⌂','Dashboard'],['calendar','▦','Calendario'],['math','∑','Matematica'],['ita','¶','Italiano'],['quiz','◆','Quiz'],['exam','◷','Simulazioni'],['progress','◎','Progressi']];
const dayMaterial=[
 {mt:[0,1],it:[0,2],me:[0,1,2,3,18,10,11],ie:[0,1,4,8]},
 {mt:[1,2],it:[3,4],me:[3,18,19,20,4,5,12],ie:[2,3,9,13,14]},
 {mt:[2,3],it:[0,5],me:[4,5,21,6,7,22,13,14],ie:[4,6,7,8,15]},
 {mt:[4,5],it:[2,5],me:[8,23,9,24,15,17],ie:[0,1,7,12]},
 {mt:[0,1,2,3,4,5],it:[0,1,2,3,4,5],me:[2,18,19,5,7,23,24,12,15],ie:[8,9,10,11,12,13,14,15]},
 {mt:[0,1,2,3,4,5],it:[0,2,3,4,5],me:[0,20,7,9,16,21],ie:[1,2,3,6,7,9,13,14,15]},
 {mt:[0,1,2,3,4,5],it:[0,1,2,3,4,5],me:[0,18,7,23,12],ie:[8,9,10,11,12,13,14,15]},
 {mt:[0,1,2,3,4,5],it:[],me:[0,18,19,20,5,7,23,24,10,17],ie:[]}
];
let state=JSON.parse(localStorage.getItem('rotta26-state')||'null')||{xp:0,done:{},answers:{},quiz:{},studySeconds:0};
let route='dashboard',timerSeconds=25*60,timerId=null,hintIndex={},currentDay=0,dayTab='plan';
const $=s=>document.querySelector(s), app=$('#app');
function save(){localStorage.setItem('rotta26-state',JSON.stringify(state));$('#xpValue').textContent=state.xp}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function pct(prefix=''){const keys=Object.keys(state.done).filter(k=>!prefix||k.startsWith(prefix));const total=prefix==='math'?exercises.math.length:prefix==='ita'?exercises.ita.length:days.length*2;return Math.min(100,Math.round(keys.filter(k=>state.done[k]).length/total*100))}
function renderNav(){ $('#nav').innerHTML=navItems.map(n=>`<button class="nav-btn ${route===n[0]?'active':''}" data-route="${n[0]}"><span>${n[1]}</span>${n[2]}</button>`).join('');document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>go(b.dataset.route))}
function go(r){route=r;$('#pageTitle').textContent=navItems.find(n=>n[0]===r)?.[2]||'Rotta 26';renderNav();render();document.querySelector('.sidebar').classList.remove('open');scrollTo(0,0)}
function updateCountdown(){let now=new Date(),target=now<ITA_EXAM?ITA_EXAM:MATH_EXAM,label=now<ITA_EXAM?'ITALIANO · 25 AGO':'MATEMATICA · 26 AGO',x=Math.max(0,target-now),d=Math.floor(x/864e5),h=Math.floor(x/36e5)%24,m=Math.floor(x/6e4)%60,s=Math.floor(x/1e3)%60;document.querySelectorAll('.countdown').forEach(el=>el.innerHTML=`<div><b>${d}</b><small>GIORNI</small></div><div><b>${h}</b><small>ORE</small></div><div><b>${m}</b><small>MINUTI</small></div><div><b>${s}</b><small>SECONDI</small></div>`);$('#sideExam').textContent=label;$('#sideCountdown').textContent=x?`${d} giorni al via`:'Prove concluse'}
function dashboard(){let di=Math.max(0,Math.min(7,new Date().getDate()-19));let day=days[di],plan=dayPlans[di],isExam=day.type.startsWith('exam');return `<section class="hero"><div class="card hero-main"><span class="kicker">MISSIONE RECUPERO</span><h2>Dal 19 agosto alle due prove. Una rotta precisa.</h2><p>Italiano il 25 agosto alle 08:10. Matematica il 26 agosto alle 08:10. Oggi conta capire il passaggio giusto — non correre.</p><div class="countdown"></div></div><div class="card today-card"><span class="date">OGGI · ${day.d}</span><h3>${day.title}</h3><p>${plan.goal}</p><div class="mini-list"><div><span>${isExam?'Durata prova':'Tempo previsto'}</span><b>${Math.floor(day.mins/60)}h ${day.mins%60}m</b></div><div><span>Attività</span><b>${plan.blocks.length}</b></div></div><button class="btn mint" style="margin-top:14px" onclick="dayDetail(${di})">Apri il piano di oggi →</button></div></section><div class="section-title"><h2>Oggi, in questo ordine</h2><span class="muted">Clicca “Apri” per iniziare</span></div><div class="card">${planBlocks(di,true)}</div><div class="grid-3" style="margin-top:20px"><div class="card subject-card math"><span class="kicker">MATEMATICA · 26 AGO</span><div class="stat">${pct('math')}%</div><div class="progress"><span style="width:${pct('math')}%"></span></div><p class="muted">Prova: 08:10–10:30.</p><button class="ghost" onclick="go('math')">Tutto il materiale</button></div><div class="card subject-card ita"><span class="kicker">ITALIANO · 25 AGO</span><div class="stat">${pct('ita')}%</div><div class="progress"><span style="width:${pct('ita')}%"></span></div><p class="muted">Prova: 08:10–09:40.</p><button class="ghost" onclick="go('ita')">Tutto il materiale</button></div><div class="card"><span class="kicker">ALLENAMENTO</span><div class="stat">${Math.floor(state.studySeconds/60)} min</div><p class="muted">Tempo registrato con il timer.</p><button class="ghost" onclick="openTimer()">Avvia timer</button></div></div>`}
function mission(k,ic,t,sub){return `<div class="mission"><div class="icon">${ic}</div><div class="grow"><b>${t}</b><small class="muted">${sub}</small></div><button class="check ${state.done[k]?'done':''}" onclick="toggleDone('${k}',this)"></button></div>`}
function toggleDone(k,b){let was=!!state.done[k];state.done[k]=!was;if(!was)state.xp+=20;else state.xp=Math.max(0,state.xp-20);save();b.classList.toggle('done');toast(state.done[k]?'+20 XP · Missione completata':'Missione riaperta')}
function calendar(){return `<div class="card exam-banner"><span class="kicker" style="color:white">PIANO UFFICIALE · 19–26 AGOSTO</span><h2>Sei giorni di preparazione, poi le due prove</h2><p><b>25 agosto:</b> Italiano 08:10–09:40. <b>26 agosto:</b> Matematica 08:10–10:30.</p></div><div class="section-title"><h2>Calendario completo</h2><span class="muted">Clicca una data per i dettagli</span></div><div class="calendar">${days.map((x,i)=>`<article class="card day-card ${i===0?'current':''}" onclick="dayDetail(${i})"><div class="day">${x.type.startsWith('exam')?'PROVA':'GIORNO '+(i+1)} · ${x.d}</div><h3>${x.title}</h3><div class="tags"><span class="tag">∑ ${x.math.split(' · ')[0]}</span><span class="tag">¶ ${x.ita.split(' · ')[0]}</span></div><p class="muted" style="margin:12px 0 0">${x.type.startsWith('exam')?'Durata: ':''}${x.mins} minuti</p></article>`).join('')}</div>`}
function planBlocks(i,compact=false){return dayPlans[i].blocks.map((b,j)=>`<div class="mission"><div class="icon">${b[0]}</div><div class="grow"><b>${j+1}. ${b[1]} · ${b[2]}</b><small class="muted">${b[3]}</small></div>${b[4]?`<button class="ghost" onclick="${compact?`dayDetail(${i})`:`closeModal();go('${b[4]}')`}">Apri</button>`:''}<button class="check ${state.done[`plan${i}-${j}`]?'done':''}" onclick="toggleDone('plan${i}-${j}',this)"></button></div>`).join('')}
function dayDetail(i){currentDay=i;dayTab='plan';route='day';$('#pageTitle').textContent=days[i].d+' · '+days[i].title;renderNav();render();scrollTo(0,0)}
function setDayTab(t){dayTab=t;render();scrollTo(0,0)}
function dailyTopicCard(k,i){let x=topics[k][i];return `<div class="card topic ${k==='ita'?'ita':''}"><div class="num">${i+1}</div><div><h3>${x[0]}</h3><p class="muted" style="margin:0">${x[1]}</p></div><button class="ghost" onclick="topicDetail('${k}',${i})">Studia</button></div>`}
function dayWorkspace(){let d=days[currentDay],p=dayPlans[currentDay],m=dayMaterial[currentDay];let tabs=`<div class="day-tabs"><button class="${dayTab==='plan'?'active':''}" onclick="setDayTab('plan')">1 · Piano</button><button class="${dayTab==='theory'?'active':''}" onclick="setDayTab('theory')">2 · Spiegazioni</button><button class="${dayTab==='practice'?'active':''}" onclick="setDayTab('practice')">3 · Esercizi</button></div>`;let body='';if(dayTab==='plan')body=`<div class="card"><span class="kicker">OBIETTIVO DEL GIORNO</span><h2>${p.goal}</h2>${p.blocks.map((b,j)=>`<div class="mission"><div class="icon">${b[0]}</div><div class="grow"><b>${j+1}. ${b[1]} · ${b[2]}</b><small class="muted">${b[3]}</small></div><button class="ghost" onclick="setDayTab('${b[4]==='exam'?'practice':b[4]==='quiz'?'practice':b[4]==='progress'?'practice':b[4]?'theory':'plan'}')">${b[4]?'Apri':'—'}</button><button class="check ${state.done[`plan${currentDay}-${j}`]?'done':''}" onclick="toggleDone('plan${currentDay}-${j}',this)"></button></div>`).join('')}</div>`;if(dayTab==='theory')body=`<div class="card day-intro"><span class="kicker">SPIEGAZIONI DEL ${d.d}</span><h2>Studia solo ciò che serve oggi</h2><p>Apri una scheda alla volta. La spiegazione appare sopra questa giornata: quando la chiudi, resti qui.</p></div>${m.mt.length?'<div class="section-title"><h2>Matematica</h2></div><div class="topic-list">'+m.mt.map(i=>dailyTopicCard('math',i)).join('')+'</div>':''}${m.it.length?'<div class="section-title"><h2>Italiano</h2></div><div class="topic-list">'+m.it.map(i=>dailyTopicCard('ita',i)).join('')+'</div>':''}<div class="actions"><button class="btn mint" onclick="setDayTab('practice')">Ho studiato: vai agli esercizi →</button></div>`;if(dayTab==='practice')body=`<div class="card day-intro"><span class="kicker">ESERCIZI DEL ${d.d}</span><h2>Tentativo → hint → soluzione</h2><p>Scrivi prima sul quaderno. Ogni esercizio ha spiegazioni progressive; apri la soluzione solo dopo un tentativo completo.</p>${currentDay===4?'<button class="btn orange" onclick="startExam(\'mathA\')">Avvia simulazione Matematica A</button>':''}</div>${m.me.length?'<div class="section-title"><h2>Matematica e problemi</h2><span class="muted">'+m.me.length+' esercizi</span></div>'+m.me.map(i=>exerciseCard('math',exercises.math[i],i)).join(''):''}${m.ie.length?'<div class="section-title"><h2>Italiano</h2><span class="muted">'+m.ie.length+' esercizi</span></div>'+m.ie.map(i=>exerciseCard('ita',exercises.ita[i],i)).join(''):''}<div class="card"><h3>Verifica finale</h3><div class="actions"><button class="ghost" onclick="startQuiz('math')">Quiz Matematica</button><button class="ghost" onclick="startQuiz('ita')">Quiz Italiano</button></div></div>`;return `<div class="card day-head"><span class="kicker">${d.type.startsWith('exam')?'PROVA':'GIORNO '+(currentDay+1)} · ${d.d}</span><h2>${d.title}</h2><p>${d.math} · ${d.ita}</p></div>${tabs}${body}`}
function subject(kind){let name=kind==='math'?'Matematica':'Italiano';return `<div class="card ${kind==='math'?'subject-card math':'subject-card ita'}"><span class="kicker">TEORIA ESSENZIALE</span><h2>${name}: prima il metodo, poi i calcoli</h2><p class="muted">Schede brevi, esempi e allenamento progressivo. Ogni soluzione resta chiusa finché non decidi di aprirla.</p></div><div class="section-title"><h2>6 schede fondamentali</h2></div><div class="topic-list">${topics[kind].map((x,i)=>`<div class="card topic ${kind==='ita'?'ita':''}"><div class="num">${i+1}</div><div><h3>${x[0]}</h3><p class="muted" style="margin:0">${x[1]}</p></div><button class="ghost" onclick="topicDetail('${kind}',${i})">Apri</button></div>`).join('')}</div><div class="section-title"><h2>Esercizi originali progressivi</h2><span class="muted">${exercises[kind].length} esercizi</span></div>${exercises[kind].map((e,i)=>exerciseCard(kind,e,i)).join('')}${kind==='math'?'<p class="source-note">Percorso costruito sul programma del prof. Fabio Frighetto, sui contenuti minimi del recupero e sulla lettera di sospensione del giudizio. Gli esercizi sono originali e coprono le tipologie richieste, senza dipendere da una singola pagina del libro.</p>':''}`}
function ruffiniLesson(){return `<div class="ruffini-box"><h3>Ruffini in una frase</h3><p>È una divisione più veloce: invece di riscrivere tutte le x, lavori soltanto con i <b>coefficienti</b>.</p><div class="sign-rule"><div>divisore<br><b>x − 2</b></div><strong>→</strong><div>numero da usare<br><b>+2</b></div></div><div class="warning"><b>Regola del segno:</b> cerca il numero che annulla la parentesi. Per x−2 usa 2; per x+3 usa −3.</div></div><h3>Esempio completo: P(x)=x³−4x²+x+6, diviso per x−2</h3><p><b>1.</b> Scrivi soltanto i coefficienti: 1, −4, 1, 6.</p><div class="ruffini-table"><span class="root">2</span><span>1</span><span>−4</span><span>1</span><span>6</span><span></span><span class="mult">2</span><span class="mult">−4</span><span class="mult">−6</span><span></span><span class="result">1</span><span class="result">−2</span><span class="result">−3</span><span class="result remainder">0</span></div><p><b>2.</b> Abbassa 1. Poi ripeti sempre lo stesso ritmo:</p><div class="formula">moltiplica per 2 → scrivi sotto → somma la colonna</div><ul><li>1·2=2; −4+2=−2</li><li>−2·2=−4; 1−4=−3</li><li>−3·2=−6; 6−6=0</li></ul><div class="read-coeff"><span>Risultati</span><b>1, −2, −3</b><span>→ x²−2x−3</span></div><p style="margin-top:12px"><b>3.</b> L’ultimo numero è il resto. È 0, quindi x−2 è davvero un fattore.</p><div class="solution"><b>Conclusione:</b> P(x)=(x−2)(x²−2x−3)=(x−2)(x−3)(x+1).</div><details class="deep"><summary>Perché il grado scende?</summary><div>Stai dividendo un polinomio di terzo grado per uno di primo grado: il quoziente è di secondo grado. Per questo i tre coefficienti 1, −2, −3 diventano x²−2x−3.</div></details><details class="deep"><summary>E se manca un termine?</summary><div>Inserisci uno zero. Per x³−5x+2 devi scrivere i coefficienti <b>1, 0, −5, 2</b>: lo zero occupa il posto di x².</div></details>`}
function ruffiniLessonFull(){return `<div class="ruffini-box"><h3>Prima di iniziare: quando si può usare?</h3><p>Ruffini si usa per dividere un polinomio per un binomio di primo grado scritto come <b>x−a</b>. Se il divisore è 2x−1, il metodo scolastico diretto non si applica nella stessa forma: prima occorre ricondurre o usare la divisione ordinaria.</p><div class="sign-rule"><div>x − 4<br><b>usa +4</b></div><div>x + 3<br><b>usa −3</b></div><div>x<br><b>usa 0</b></div></div><div class="warning"><b>Trucco sicuro:</b> trova il numero che rende il divisore uguale a zero. x+3=0 → x=−3.</div></div><h3>Esempio 1 · divisione con resto non nullo</h3><div class="formula">P(x)=2x³−3x²+4x−5, divisore x−2</div><p>Coefficienti: 2, −3, 4, −5. Uso 2.</p><ul><li>Abbasso 2.</li><li>2·2=4; −3+4=1.</li><li>1·2=2; 4+2=6.</li><li>6·2=12; −5+12=7.</li></ul><div class="solution"><b>Quoziente:</b> 2x²+x+6. <b>Resto:</b> 7. Quindi x−2 non è un fattore e P(2)=7.</div><h3 style="margin-top:22px">Esempio 2 · termine mancante</h3><div class="formula">P(x)=x⁴−5x²+4, divisore x−1</div><p>Non scrivere 1,−5,4: mancano x³ e x. La riga corretta è <b>1, 0, −5, 0, 4</b>.</p><ul><li>Con a=1 ottieni: 1, 1, −4, −4 e resto 0.</li><li>Il quoziente è x³+x²−4x−4.</li><li>Raccoglimento parziale: x²(x+1)−4(x+1)=(x+1)(x²−4).</li></ul><div class="solution">P(x)=(x−1)(x+1)(x−2)(x+2).</div><h3 style="margin-top:22px">Esempio 3 · la radice non è data</h3><div class="formula">P(x)=x³+3x²−4x−12</div><p>Per un polinomio monico, prova i divisori interi di −12: ±1, ±2, ±3, ±4, ±6, ±12. Conviene partire dai piccoli.</p><ul><li>P(1)=−12, quindi 1 non va.</li><li>P(2)=8+12−8−12=0: x−2 è un fattore.</li><li>Ruffini con 2 dà x²+5x+6=(x+2)(x+3).</li></ul><div class="solution">P(x)=(x−2)(x+2)(x+3).</div><details class="deep"><summary>Come leggere il risultato senza sbagliare grado</summary><div>Se P è di grado 4, il quoziente è di grado 3. Quattro coefficienti finali diventano, nell’ordine, coefficienti di x³, x², x e termine noto. L’ultimo numero separato è sempre il resto.</div></details><details class="deep"><summary>Controllo completo della divisione</summary><div>Deve valere sempre: <b>P(x)=(x−a)·Q(x)+R</b>. Se R=0, hai una vera scomposizione. Puoi anche controllare rapidamente il resto calcolando P(a).</div></details><details class="deep"><summary>Strategia all’esame</summary><div>1) Ordina e completa i gradi. 2) Scrivi il numero col segno corretto. 3) Esegui senza saltare colonne. 4) Evidenzia il resto. 5) Scrivi il quoziente con le potenze. 6) Se il resto è zero, continua la scomposizione.</div></details>`}
function geometryLesson(){return `<h3>Guarda prima la figura, poi leggi la dimostrazione</h3><div class="geometry-visual"><figure class="geo-card"><svg viewBox="0 0 260 190" role="img" aria-label="Triangolo isoscele con bisettrice"><polygon class="geo-fill" points="130,18 35,165 225,165"/><line class="geo-line" x1="130" y1="18" x2="130" y2="165"/><path class="geo-mark" d="M116 42 A25 25 0 0 1 130 50 M130 50 A25 25 0 0 1 144 42"/><text class="geo-label" x="126" y="14">A</text><text class="geo-label" x="20" y="178">B</text><text class="geo-label" x="230" y="178">C</text><text class="geo-label" x="126" y="182">D</text></svg><figcaption><b>Triangolo isoscele:</b> AB=AC. AD divide l’angolo A in due parti congruenti.</figcaption></figure><figure class="geo-card"><svg viewBox="0 0 260 190" role="img" aria-label="Rette parallele tagliate da trasversale"><line class="geo-line" x1="20" y1="48" x2="240" y2="48"/><line class="geo-line" x1="20" y1="142" x2="240" y2="142"/><line class="geo-line" x1="85" y1="10" x2="175" y2="180"/><path class="geo-mark" d="M105 48 A25 25 0 0 1 117 70"/><path class="geo-mark" d="M143 120 A25 25 0 0 1 155 142"/><text class="geo-label" x="210" y="40">r</text><text class="geo-label" x="210" y="134">s</text><text class="geo-label" x="178" y="176">t</text></svg><figcaption><b>r ∥ s:</b> gli angoli alterni interni evidenziati sono congruenti.</figcaption></figure></div><div class="solution"><b>Dimostrazione modello:</b> nei triangoli ABD e ACD, AB=AC per ipotesi, AD è comune e BÂD=DÂC perché AD è bisettrice. Per il criterio LAL i triangoli sono congruenti; quindi BD=DC.</div>`}
function topicDetail(k,i){let x=topics[k][i],d=topicDeep[k][i],special=k==='math'&&i===1?ruffiniLessonFull():k==='math'&&i===5?geometryLesson():'';openModal(`<span class="kicker">SCHEDA ${i+1} · ${k==='math'?'MATEMATICA':'ITALIANO'}</span><h2>${x[0]}</h2><p class="lesson-lead">${d.lead}</p>${special}<div class="lesson-nav"><span class="lesson-pill">① Capisci</span><span class="lesson-pill">② Applica</span><span class="lesson-pill">③ Controlla</span></div><h3>Il metodo, passo per passo</h3><div class="lesson-steps">${d.steps.map(s=>`<div class="lesson-step"><div>${s}</div></div>`).join('')}</div>${special?'':'<h3 style="margin-top:22px">Esempio commentato</h3><div class="formula">'+d.example+'</div>'}<details class="deep"><summary>Errori frequenti da evitare</summary><div><ul>${d.errors.map(e=>`<li>${e}</li>`).join('')}</ul></div></details><details class="deep"><summary>Approfondisci l’argomento</summary><div><p>${d.deep}</p><div class="warning"><b>All’esame:</b> mostra il metodo e motiva i passaggi; il solo risultato non basta.</div></div></details><details class="deep"><summary>Richiamo essenziale</summary><div><p>${x[1]}</p><div class="solution">${x[2]}</div></div></details><button class="btn" style="margin-top:18px" onclick="closeModal()">Torna alla giornata</button>`)}
function exerciseCard(k,e,i){let key=`${k}${i}`;return `<article class="exercise card"><div class="exercise-head"><div><span class="difficulty">${e.level}</span><h3>${e.t}</h3><p>${e.q}</p></div><button class="check ${state.done[key]?'done':''}" onclick="completeExercise('${key}',this)"></button></div><div class="exercise-body"><textarea class="answer" placeholder="Scrivi qui passaggi e risposta…" oninput="saveAnswer('${key}',this.value)">${state.answers[key]||''}</textarea><div id="hint-${key}"></div><div id="sol-${key}"></div><div class="actions"><button class="ghost" onclick="showHint('${k}',${i})">💡 Mostra un indizio</button><button class="ghost" onclick="showSolution('${k}',${i})">✓ Soluzione guidata</button></div></div></article>`}
function saveAnswer(k,v){state.answers[k]=v;save()}
function showHint(k,i){let key=`${k}${i}`,n=hintIndex[key]||0,e=exercises[k][i];n=Math.min(n,e.h.length-1);$(`#hint-${key}`).innerHTML=`<div class="hint"><b>Indizio ${n+1}/${e.h.length}</b><br>${e.h[n]}</div>`;hintIndex[key]=Math.min(n+1,e.h.length-1)}
function showSolution(k,i){let key=`${k}${i}`;$(`#sol-${key}`).innerHTML=`<div class="solution"><b>Soluzione guidata</b><br>${exercises[k][i].s}</div>`}
function completeExercise(k,b){let was=!!state.done[k];state.done[k]=!was;state.xp=Math.max(0,state.xp+(was?-10:10));save();b.classList.toggle('done');toast(was?'Esercizio riaperto':'+10 XP · Esercizio completato')}
function quizPage(){return `<div class="grid-2"><div class="card subject-card math"><span class="kicker">QUIZ MATEMATICA</span><h2>5 domande · soglia 4/5</h2><p>Riconoscimento rapido di metodi e regole.</p><button class="btn" onclick="startQuiz('math')">Inizia</button></div><div class="card subject-card ita"><span class="kicker">QUIZ ITALIANO</span><h2>5 domande · soglia 4/5</h2><p>Narratologia, grammatica e metodo.</p><button class="btn" onclick="startQuiz('ita')">Inizia</button></div></div>`}
function startQuiz(k){let qs=quizzes[k];openModal(`<span class="kicker">QUIZ ${k==='math'?'MATEMATICA':'ITALIANO'}</span><h2>Rispondi a tutte le domande</h2><div id="quizQuestions">${qs.map((q,i)=>`<div class="sim-question"><b>${i+1}. ${q[0]}</b>${q[1].map((o,j)=>`<button class="quiz-option" data-qi="${i}" data-oj="${j}" onclick="selectOption(this)">${o}</button>`).join('')}</div>`).join('')}</div><button class="btn" onclick="gradeQuiz('${k}')">Correggi quiz</button><div id="quizResult"></div>`)}
function selectOption(b){document.querySelectorAll(`[data-qi="${b.dataset.qi}"]`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}
function gradeQuiz(k){let score=0;quizzes[k].forEach((q,i)=>{let sel=document.querySelector(`[data-qi="${i}"].selected`);document.querySelectorAll(`[data-qi="${i}"]`).forEach(x=>{x.disabled=true;if(+x.dataset.oj===q[2])x.classList.add('correct')});if(sel&&+sel.dataset.oj===q[2])score++;else if(sel)sel.classList.add('wrong')});state.quiz[k]=Math.max(state.quiz[k]||0,score);state.xp+=score*5+(score>=4?25:0);save();$('#quizResult').innerHTML=`<div class="solution"><h3>${score}/5 ${score>=4?'· Quiz superato! 🎉':'· Ripassa e riprova'}</h3><p>${score>=4?'Bonus +25 XP sbloccato.':'Apri le schede essenziali sugli errori.'}</p></div>`}
function examPage(){return `<div class="card exam-banner"><span class="kicker" style="color:white">MODALITÀ ESAME</span><h2>Prove costruite sui documenti scolastici</h2><p>Programma Frighetto, contenuti minimi e lettera di sospensione. Le soluzioni compaiono solo dopo la consegna.</p></div><div class="section-title"><h2>Simulazioni di Matematica · 120 minuti</h2></div><div class="exam-grid"><div class="card"><span class="kicker">MATEMATICA A</span><h3>Prova completa</h3><p class="muted">8 quesiti · algebra, equazioni, disequazioni, problema e geometria</p><button class="btn orange" onclick="startExam('mathA')">Avvia prova A</button></div><div class="card"><span class="kicker">MATEMATICA B</span><h3>Seconda prova completa</h3><p class="muted">8 quesiti originali · copertura dell’intero programma minimo</p><button class="btn orange" onclick="startExam('mathB')">Avvia prova B</button></div><div class="card"><span class="kicker">ITALIANO</span><h3>Prova completa</h3><p class="muted">Testo + grammatica · 90 minuti</p><button class="btn" onclick="startExam('ita')">Avvia prova</button></div></div><div class="card" style="margin-top:18px"><h3>Distribuzione delle prove di Matematica</h3><p>Calcolo letterale e prodotti notevoli; scomposizioni; divisione e Ruffini; frazioni algebriche con C.E.; equazioni intere e fratte; disequazioni; problemi con equazioni; geometria e dimostrazione.</p></div>`}
function startExam(k){let set=examSets[k],pool,minutes,title;if(set){pool=set.questions.map(q=>({t:q[0],q:q[1],s:q[2]}));minutes=set.minutes;title=set.title}else{pool=exercises.ita.slice(0,8);minutes=90;title='Italiano · Simulazione'}timerSeconds=minutes*60;openModal(`<span class="kicker">${title}</span><div class="timer-display" id="examClock">${fmt(timerSeconds)}</div><p class="muted" style="text-align:center">Il timer parte ora. Niente hint o soluzioni prima della consegna.</p>${pool.map((e,i)=>`<div class="sim-question"><b>${i+1}. ${e.t}</b><p>${e.q}</p><textarea class="answer" placeholder="Risposta e passaggi…"></textarea></div>`).join('')}<button class="btn orange" onclick="finishExam('${k}')">Consegna e correggi</button>`);startTimer($('#examClock'))}
function finishExam(k){clearInterval(timerId);timerId=null;state.xp+=50;state.done[`exam${k}`]=true;save();let set=examSets[k],solutions=set?set.questions.map((q,i)=>`<div class="solution"><b>${i+1}. ${q[0]}</b><br>${q[2]}</div>`).join(''):'<div class="solution">Confronta le risposte con le soluzioni guidate della sezione Italiano.</div>';$('#modalBody').innerHTML=`<span class="kicker">PROVA CONSEGNATA</span><h2>+50 XP · Correzione guidata</h2><p>Segna ogni errore come <b>metodo</b>, <b>calcolo/forma</b> oppure <b>distrazione</b>. Poi rifai senza guardare solo i quesiti sbagliati.</p>${solutions}`}
function progressPage(){let badges=[['🌱','Primo passo',state.xp>=10],['🔥','100 XP',state.xp>=100],['∑','Algebrista',pct('math')>=50],['¶','Lettore attento',pct('ita')>=50],['◆','Quiz 4/5',(state.quiz.math||0)>=4||(state.quiz.ita||0)>=4],['⏱','Ora di studio',state.studySeconds>=3600],['🏁','Simulatore',state.done.exammath||state.done.examita],['⭐','Rotta completa',state.xp>=400]];return `<div class="grid-3"><div class="card"><span class="kicker">PUNTI</span><div class="stat">${state.xp} XP</div><p class="muted">Ogni esercizio vale 10 XP, ogni missione 20.</p></div><div class="card"><span class="kicker">MATEMATICA</span><div class="stat">${pct('math')}%</div><div class="progress"><span style="width:${pct('math')}%"></span></div></div><div class="card"><span class="kicker">ITALIANO</span><div class="stat">${pct('ita')}%</div><div class="progress"><span style="width:${pct('ita')}%"></span></div></div></div><div class="section-title"><h2>Badge</h2></div><div class="badge-grid">${badges.map(b=>`<div class="badge ${b[2]?'':'locked'}"><span>${b[0]}</span><b>${b[1]}</b><small>${b[2]?'Sbloccato':'Da sbloccare'}</small></div>`).join('')}</div><div class="card" style="margin-top:20px"><h3>I tuoi dati restano su questo Mac</h3><p class="muted">Progressi e risposte sono salvati solo nel browser. Puoi esportare una copia o azzerare tutto.</p><div class="actions"><button class="ghost" onclick="exportData()">Esporta progressi</button><button class="ghost" onclick="resetData()">Azzera dati</button></div></div>`}
function exportData(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='progressi-filippo.json';a.click();URL.revokeObjectURL(a.href)}
function resetData(){if(confirm('Vuoi davvero cancellare progressi, punti e risposte?')){localStorage.removeItem('rotta26-state');state={xp:0,done:{},answers:{},quiz:{},studySeconds:0};save();render();toast('Progressi azzerati')}}
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('show')}
function closeModal(){clearInterval(timerId);$('#modal').classList.remove('show')}
function openTimer(){openModal(`<span class="kicker">TIMER DI CONCENTRAZIONE</span><h2>Una sessione, un obiettivo</h2><div class="timer-display" id="clock">${fmt(timerSeconds)}</div><div class="actions" style="justify-content:center"><button class="btn mint" onclick="startTimer($('#clock'))">Avvia</button><button class="ghost" onclick="pauseTimer()">Pausa</button><button class="ghost" onclick="setTimer(25)">25 min</button><button class="ghost" onclick="setTimer(50)">50 min</button></div><p class="muted" style="text-align:center;margin-top:18px">Il tempo completato viene registrato nei progressi.</p>`)}
function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function startTimer(el){if(timerId)return;timerId=setInterval(()=>{if(timerSeconds>0){timerSeconds--;state.studySeconds++;if(timerSeconds%15===0)save();if(el)el.textContent=fmt(timerSeconds)}else{clearInterval(timerId);timerId=null;save();toast('Sessione completata!')}} ,1000)}
function pauseTimer(){clearInterval(timerId);timerId=null;save()}
function setTimer(m){pauseTimer();timerSeconds=m*60;let el=$('#clock');if(el)el.textContent=fmt(timerSeconds)}
function render(){app.innerHTML=route==='dashboard'?dashboard():route==='calendar'?calendar():route==='day'?dayWorkspace():route==='math'?subject('math'):route==='ita'?subject('ita'):route==='quiz'?quizPage():route==='exam'?examPage():progressPage();updateCountdown();save()}
$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#timerOpen').onclick=openTimer;$('#mobileNav').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
function richTopicDetail(k,i){let x=topics[k][i],d=topicDeep[k][i],special=k==='math'&&i===1?ruffiniLessonFull():k==='math'&&i===5?geometryLesson():'',more=extraExamples[k][i];openModal(`<span class="kicker">SCHEDA ${i+1} · ${k==='math'?'MATEMATICA':'ITALIANO'}</span><h2>${x[0]}</h2><p class="lesson-lead">${d.lead}</p>${special}<div class="lesson-nav"><span class="lesson-pill">① Capisci</span><span class="lesson-pill">② Applica</span><span class="lesson-pill">③ Controlla</span></div><h3>Il metodo, passo per passo</h3><div class="lesson-steps">${d.steps.map(s=>`<div class="lesson-step"><div>${s}</div></div>`).join('')}</div>${special?'':'<h3 style="margin-top:22px">Esempio commentato</h3><div class="formula">'+d.example+'</div>'}<details class="deep" open><summary>Altri esempi spiegati</summary><div>${more.map(e=>`<h4>${e[0]}</h4><div class="formula">${e[1]}</div>`).join('')}</div></details><details class="deep"><summary>Errori frequenti da evitare</summary><div><ul>${d.errors.map(e=>`<li>${e}</li>`).join('')}</ul></div></details><details class="deep"><summary>Approfondisci l’argomento</summary><div><p>${d.deep}</p><div class="warning"><b>All’esame:</b> mostra il metodo e motiva i passaggi; il solo risultato non basta.</div></div></details><details class="deep"><summary>Richiamo essenziale</summary><div><p>${x[1]}</p><div class="solution">${x[2]}</div></div></details><button class="btn" style="margin-top:18px" onclick="closeModal()">Torna alla giornata</button>`)}
topicDetail=richTopicDetail;
renderNav();render();updateCountdown();setInterval(updateCountdown,1000);
