// Pacchetto di consolidamento finale: più teoria, esercizi e simulazioni originali.
const masteryTopic=(kind,title,summary,quick,lead,steps,errors,deep,example,examples)=>addTopic(kind,title,summary,quick,{lead,steps,errors,deep,example},examples);

masteryTopic('math','Potenze, frazioni e segni','Ripassa gerarchia delle operazioni, potenze e calcolo con frazioni: gli errori di base possono compromettere tutto l’esercizio.','(−2)³=−8, mentre −2²=−4: le parentesi cambiano la base.','Prima dell’algebra serve un calcolo numerico sicuro. Segni, parentesi, potenze e denominatori vanno gestiti in un ordine stabile.',['Risolvi parentesi interne e potenze.','Trasforma divisioni tra frazioni in moltiplicazioni per il reciproco.','Usa il m.c.m. per somme e differenze.','Semplifica prima di moltiplicare, quando possibile.','Controlla segno e ordine di grandezza.'],['Dimenticare che −2² significa −(2²).','Sommare numeratore con numeratore e denominatore con denominatore.','Capovolgere la frazione sbagliata.','Ignorare la priorità delle potenze.'],'Regole: aⁿ·aᵐ=aⁿ⁺ᵐ; aⁿ:aᵐ=aⁿ⁻ᵐ con a≠0; (aⁿ)ᵐ=aⁿᵐ; a⁰=1 con a≠0. Una potenza con esponente pari è non negativa; con esponente dispari conserva il segno della base.','3/4−(1/2):(−2/3)=3/4−(1/2)(−3/2)=3/4+3/4=3/2.',[['Segni','(−3)²=9; −3²=−9; (−3)³=−27.'],['Frazioni','2/3+5/6=4/6+5/6=3/2.']]);
masteryTopic('math','Equazioni: discussione e controllo','Un’equazione di primo grado può essere determinata, impossibile o indeterminata. Il controllo finale distingue un risultato da una soluzione.','0x=5: impossibile. 0x=0: indeterminata.','Non tutte le equazioni terminano con x uguale a un numero: dopo le riduzioni devi interpretare ciò che rimane.',['Elimina parentesi e denominatori ammessi.','Riduci separatamente i due membri.','Porta i termini con x da una parte.','Se resta ax=b con a≠0, calcola x=b/a.','Se resta 0=b, classifica; poi verifica nell’equazione iniziale.'],['Dividere per zero quando il coefficiente di x scompare.','Chiamare x=0 il caso 0x=0.','Dimenticare le C.E. nelle equazioni fratte.','Controllare soltanto i passaggi e non il testo iniziale.'],'Determinata: una soluzione. Impossibile: nessuna soluzione, perché compare un’uguaglianza falsa. Indeterminata: ogni valore ammesso è soluzione, perché compare un’identità. Nelle fratte l’insieme delle soluzioni resta limitato dalle C.E.','2(x−3)+5=2x−1 → 2x−6+5=2x−1 → −1=−1: indeterminata, quindi tutti i reali.',[['Impossibile','4(x+1)=4x+7 → 4=7: nessuna soluzione.'],['Fratta','Se dopo i calcoli ottieni x=2 ma la C.E. vieta 2, l’equazione non ha soluzioni.']]);
masteryTopic('math','Disequazioni fratte e studio del segno','Porta tutto a un’unica frazione e studia il segno di numeratore e denominatore su una tabella. I valori esclusi restano sempre esclusi.','(x−2)/(x+1)>0: punti critici −1 e 2; soluzione x<−1 oppure x>2.','Una frazione è positiva quando numeratore e denominatore hanno lo stesso segno, negativa quando hanno segno opposto.',['Porta tutti i termini al primo membro.','Riduci a un’unica frazione scomposta.','Trova zeri del numeratore e valori vietati del denominatore.','Ordina i punti critici sulla retta e compila i segni.','Scegli gli intervalli richiesti; includi gli zeri solo con ≤ o ≥, mai i valori vietati.'],['Moltiplicare per un denominatore di segno ignoto.','Includere un valore che annulla il denominatore.','Dimenticare lo zero del numeratore con ≥ o ≤.','Studiare i singoli termini prima di ridurre a una frazione.'],'Il metodo della tabella dei segni evita di decidere a priori il verso quando si moltiplica per un’espressione contenente x. Ogni fattore cambia segno attraversando uno zero semplice.','(x−3)/(x+2)≤0. Punti −2 vietato e 3 zero. Segni: positivo prima di −2, negativo tra −2 e 3, positivo dopo 3. Soluzione (−2,3].',[['Prodotto','(x−1)(x+4)≥0 → x≤−4 oppure x≥1.'],['Valore vietato','Il pallino di un denominatore è sempre vuoto.']]);

masteryTopic('ita','Punteggiatura e sintassi della frase','La punteggiatura organizza il pensiero: separa nuclei, segnala rapporti logici e impedisce ambiguità.','Mai la virgola tra soggetto e predicato, salvo inciso chiaramente delimitato.','Una frase corretta non è soltanto priva di errori ortografici: deve far capire subito chi compie l’azione e come le idee sono collegate.',['Individua il nucleo soggetto-predicato.','Separa proposizioni complete con punto, punto e virgola o connettivo.','Usa due punti per spiegazione o elenco.','Chiudi gli incisi con due virgole o due trattini.','Rileggi ad alta voce e controlla periodi troppo lunghi.'],['Virgola tra soggetto e verbo.','Unire frasi autonome soltanto con una virgola.','Usare i due punti dopo un verbo che regge direttamente l’elenco.','Mettere virgole secondo le pause del respiro senza guardare la sintassi.'],'Il punto dà autonomia; il punto e virgola separa nuclei collegati; i due punti introducono conseguenza, spiegazione, elenco o discorso; la virgola delimita elementi coordinati, subordinate e incisi. La punteggiatura può cambiare il significato.','Scorretto: “Marta, aprì la porta, vide il buio e, accese la luce.” Corretto: “Marta aprì la porta, vide il buio e accese la luce.”',[['Inciso','Ulisse, stanco ma prudente, non rivelò il nome.'],['Due punti','Capì il pericolo: la porta era rimasta aperta.']]);
masteryTopic('ita','Coesione, connettivi e paragrafi','Un buon testo guida il lettore con pronomi, riprese lessicali, connettivi e paragrafi costruiti intorno a un’idea.','Causa: perché, poiché; conseguenza: quindi, perciò; contrasto: ma, tuttavia.','La coesione lega le frasi; la coerenza fa sì che tutte contribuiscano allo stesso scopo comunicativo.',['Scrivi una frase-tema per ogni paragrafo.','Sostituisci ripetizioni inutili con pronomi o sinonimi chiari.','Scegli il connettivo dal rapporto logico reale.','Mantieni coerenti persona, tempo verbale e punto di vista.','Controlla che ogni paragrafo prepari il successivo.'],['Usare “infatti” per una conseguenza.','Inserire pronomi con referente ambiguo.','Cambiare tempo verbale senza motivo.','Accumulare idee diverse nello stesso paragrafo.'],'Connettivi utili: inoltre (aggiunta), infatti/perché (spiegazione o causa), quindi/perciò (conseguenza), tuttavia/invece (contrasto), per esempio (esemplificazione), in conclusione (chiusura). Non vanno aggiunti meccanicamente: devono rendere esplicita una relazione già pensata.','Luca studiò molto; tuttavia era agitato. Perciò preparò una scaletta, che gli permise di rispondere con ordine.',[['Referente','“Marta parlò con Anna e lei sorrise” è ambiguo: ripeti il nome necessario.'],['Paragrafo','Idea centrale → esempio/prova → spiegazione → frase di raccordo.']]);
masteryTopic('ita','Comprensione e risposta aperta','Prima di rispondere individua comando, oggetto e prove richieste. Una risposta completa afferma, dimostra e spiega.','Domanda “Perché?”: tesi + elemento del testo + relazione causale.','Molti punti si perdono non per ignoranza, ma perché la risposta non svolge tutte le parti della consegna o resta generica.',['Cerchia i verbi della consegna: individua, spiega, confronta, motiva.','Trasforma la domanda nell’inizio della risposta.','Formula una risposta diretta nella prima frase.','Aggiungi una prova precisa o un breve riferimento al testo.','Spiega l’effetto e rileggi verificando ogni richiesta.'],['Riassumere quando viene chiesta un’interpretazione.','Copiare una frase senza spiegarla.','Scrivere “secondo me” senza prova.','Dimenticare una delle due parti di una domanda doppia.'],'Schema P.E.E. ampliato: Punto (risposta), Evidenza (parola, gesto, scelta narrativa), Spiegazione (perché l’evidenza sostiene il punto). Nel confronto aggiungi somiglianza, differenza e criterio comune.','La scena comunica paura (P). Il corridoio è vuoto e i colpi restano senza origine (E). Le informazioni limitate condividono l’incertezza del personaggio con il lettore (E).',[['Confronto','“Entrambi…, mentre…” rende espliciti criterio comune e differenza.'],['Citazione','Bastano poche parole precise, integrate grammaticalmente nella risposta.']]);

exercises.math.push(
 {t:'Potenze e segni',q:'Calcola: −2² +(−2)³−(−3)².',level:'BASE',h:['Senza parentesi, −2²=−4.','(−2)³=−8 e (−3)²=9.'],s:'−4−8−9=−21.'},
 {t:'Frazioni numeriche',q:'Calcola 5/6−[1/3:(−2/5)].',level:'MEDIO',h:['La divisione diventa (1/3)(−5/2).','Quindi sottrai un numero negativo.'],s:'1/3:(−2/5)=−5/6. Allora 5/6−(−5/6)=10/6=5/3.'},
 {t:'Scomposizione · raccoglimento parziale',q:'Scomponi completamente 3x³−6x²−12x+24.',level:'MEDIO',h:['Raggruppa i primi due e gli ultimi due termini.','3x²(x−2)−12(x−2).'],s:'(x−2)(3x²−12)=3(x−2)(x²−4)=3(x−2)²(x+2).'},
 {t:'Ruffini · radice negativa',q:'Scomponi x³+4x²+x−6 sapendo che −2 è una radice.',level:'MEDIO',h:['Il fattore è x+2; usa −2.','Il quoziente è x²+2x−3.'],s:'Ruffini dà resto 0 e Q=x²+2x−3=(x+3)(x−1). Quindi (x+2)(x+3)(x−1).'},
 {t:'Frazione algebrica · prodotto',q:'Semplifica [(x²−4)/(x²−x−2)]·[(x−1)/(x+2)], indicando le C.E.',level:'AVANZATO',h:['Scomponi x²−4 e x²−x−2.','Conserva tutti i valori vietati dei denominatori originali.'],s:'C.E. x≠2,−1,−2. [(x−2)(x+2)/((x−2)(x+1))]·[(x−1)/(x+2)]=(x−1)/(x+1), con le C.E. originali.'},
 {t:'Equazione impossibile',q:'Risolvi e classifica: 5(2x−1)−3=10x+4.',level:'MEDIO',h:['Riduci il primo membro.','Ottieni −8=4.'],s:'10x−5−3=10x+4 → −8=4, uguaglianza falsa: equazione impossibile, nessuna soluzione.'},
 {t:'Equazione fratta · soluzione esclusa',q:'Risolvi (x+2)/(x−1)=3/(x−1).',level:'MEDIO',h:['C.E. x≠1.','Moltiplicando ottieni x+2=3.'],s:'C.E. x≠1. L’equazione produce x=1, ma è vietato. Quindi non esistono soluzioni.'},
 {t:'Disequazione fratta',q:'Risolvi (x−4)/(x+2)≥0.',level:'AVANZATO',h:['Punti critici: −2 vietato, 4 zero.','Studia i tre intervalli.'],s:'La frazione è positiva per x<−2 e x>4, nulla in x=4. Soluzione: x<−2 oppure x≥4.'},
 {t:'Problema · lavoro',q:'Due persone completano insieme 42 schede. Filippo ne completa 6 più del doppio dell’altra persona. Quante schede completa ciascuno?',level:'PROBLEMA',h:['Poni x le schede dell’altra persona.','x+(2x+6)=42.'],s:'3x+6=42 → x=12. L’altra persona completa 12 schede e Filippo 30. Controllo: 12+30=42.'},
 {t:'Problema · velocità media',q:'Un autobus percorre 180 km. Per i primi 60 km viaggia a 60 km/h; completa il viaggio in 3 ore. Qual è la velocità media nei restanti 120 km?',level:'PROBLEMA',h:['I primi 60 km richiedono 1 ora.','Restano 120 km e 2 ore.'],s:'Tempo residuo 3−1=2 ore. Velocità nei restanti 120 km: 120/2=60 km/h.'},
 {t:'Geometria · angoli esterni',q:'In un triangolo due angoli interni misurano 48° e 67°. Calcola il terzo angolo e l’angolo esterno a esso adiacente.',level:'MEDIO',h:['La somma interna è 180°.','L’angolo esterno è supplementare al terzo interno.'],s:'Terzo angolo=180°−48°−67°=65°. Esterno adiacente=180°−65°=115°, uguale anche alla somma dei due interni non adiacenti.'},
 {t:'Geometria · dimostrazione',q:'In un parallelogramma ABCD dimostra che i triangoli ABC e CDA sono congruenti.',level:'AVANZATO',h:['Usa i lati opposti e la diagonale AC.','AB=CD, BC=AD, AC comune: applica il 3° criterio di congruenza (LLL).'],s:'Nel parallelogramma i lati opposti sono congruenti: AB=CD e BC=AD. Inoltre AC è comune. I triangoli ABC e CDA sono congruenti per il 3° criterio di congruenza (LLL).'}
);

exercises.ita.push(
 {t:'Punteggiatura',q:'Correggi: “Il capitano, osservò il cielo vide le nuvole scure, e ordinò il rientro.”',level:'BASE',h:['Non separare soggetto e predicato.','Serve un segno tra due predicati non coordinati chiaramente.'],s:'“Il capitano osservò il cielo, vide le nuvole scure e ordinò il rientro.”'},
 {t:'Connettivi',q:'Completa con connettivi adatti: “Aveva studiato con metodo; ___ era ancora insicuro. ___ preparò una scaletta e rispose con ordine.”',level:'BASE',h:['Prima relazione: contrasto. Seconda: conseguenza.','Possibili: tuttavia, perciò.'],s:'“Aveva studiato con metodo; tuttavia era ancora insicuro. Perciò preparò una scaletta e rispose con ordine.”'},
 {t:'Analisi logica completa',q:'Analizza: “Dopo il lungo viaggio, Odisseo raccontò con prudenza le sue avventure al re dei Feaci.”',level:'MEDIO',h:['Trova raccontò, poi chi, che cosa, a chi, quando e come.','“dei Feaci” dipende da re.'],s:'Tempo: dopo il viaggio; attributo: lungo; soggetto: Odisseo; PV: raccontò; modo: con prudenza; oggetto: le avventure; attributo: sue; termine: al re; specificazione: dei Feaci.'},
 {t:'Verbi e rapporti temporali',q:'Analizza le forme: “Quando arrivò, Marta aveva già concluso ciò che le era stato assegnato.”',level:'MEDIO',h:['arrivò, aveva concluso, era stato assegnato.','L’ultima forma è passiva.'],s:'arrivò: indicativo passato remoto, 3ª singolare, attiva; aveva concluso: indicativo trapassato prossimo, 3ª singolare, attiva; era stato assegnato: indicativo trapassato prossimo, 3ª singolare, passiva.'},
 {t:'Ortografia e punteggiatura',q:'Correggi: “Pultroppo non sò se Luca verrà, però se cè tempo gli telefonerò senzaltro.”',level:'MEDIO',h:['Controlla purtroppo, so, c’è, senz’altro.','Inserisci una virgola dove separa la subordinata.'],s:'“Purtroppo non so se Luca verrà; però, se c’è tempo, gli telefonerò senz’altro.”'},
 {t:'Risposta P.E.E.',q:'Rispondi in 6–8 righe: perché la focalizzazione interna può aumentare la suspense?',level:'AVANZATO',h:['Il lettore sa soltanto ciò che percepisce il personaggio.','Aggiungi un esempio di informazione nascosta.'],s:'Risposta modello: La focalizzazione interna aumenta la suspense perché limita le informazioni del lettore a quelle possedute dal personaggio. Se il protagonista sente passi ma non ne conosce l’origine, anche il lettore resta nell’incertezza. La percezione parziale impedisce di anticipare il pericolo e rende significativi rumori, esitazioni e ipotesi sbagliate.'},
 {t:'Testo narrativo · La fermata',q:`Leggi il testo e rispondi.

Alle sette meno dieci Nora era già alla fermata. La strada, dopo il temporale, rifletteva le insegne ancora accese. Nella tasca stringeva la busta con la domanda d’iscrizione: mancava soltanto la firma di sua madre. Avevano discusso fino a tardi. La madre temeva che il corso in città fosse troppo impegnativo; Nora, invece, non voleva rinunciare prima ancora di provare. Quando l’autobus comparve in fondo al viale, vide una figura correre sotto i portici. Era sua madre. Non disse nulla: le porse la busta, ora firmata, e le sistemò il cappuccio. Nora salì. Dal finestrino la vide diventare più piccola, immobile accanto alla pensilina. Solo allora comprese che quella firma non cancellava la paura della madre: significava che aveva deciso di fidarsi nonostante la paura.

Domande: 1) Dividi in sequenze. 2) Indica narratore e focalizzazione con una prova. 3) Spiega il significato della firma. 4) Individua il cambiamento di Nora. 5) Riassumi in 70 parole.`,level:'TESTO COMPLETO',h:['Sequenze: attesa; antefatto del conflitto; arrivo della madre; partenza e comprensione.','La voce è esterna, ma segue percezioni e comprensione di Nora.'],s:'1) Attesa descrittivo-narrativa; analessi sulla discussione; arrivo e consegna; partenza e riflessione. 2) Narratore esterno, focalizzazione interna su Nora: conosciamo ciò che stringe, vuole e comprende. 3) La firma simboleggia fiducia e sostegno, non assenza di paura. 4) Nora passa dal vedere la madre come ostacolo al comprenderne il coraggio affettivo. 5) Il riassunto deve mantenere attesa, conflitto, firma, partenza e nuova comprensione.'},
 {t:'Testo narrativo · Il quaderno blu',q:`Leggi il testo e rispondi.

Davide riconobbe il quaderno dalla macchia d’inchiostro sulla copertina. Era sul banco in fondo, dove nessuno sedeva da mesi. Lo aprì e trovò, tra esercizi incompleti, una lista di progetti: costruire un aquilone, imparare cinque accordi, tornare a parlare con Samir. Il quaderno apparteneva a Pietro, trasferitosi senza salutare dopo una lite con la classe. Davide ricordò di aver riso quando Pietro aveva presentato l’aquilone storto. Quella risata, allora insignificante, ora gli sembrò pesante. Fotografò la pagina e cercò il vecchio numero. Scrisse tre volte un messaggio e tre volte lo cancellò. Alla fine inviò soltanto: “Ho trovato il tuo quaderno. Se vuoi, possiamo finire l’aquilone”. La risposta arrivò la sera: una fotografia del cielo e una parola, “Quando?”.

Domande: 1) Ricostruisci fabula e intreccio. 2) Individua l’analessi. 3) Quale conflitto vive Davide? 4) Spiega il finale. 5) Proponi un titolo motivato.`,level:'TESTO COMPLETO',h:['L’episodio della risata precede il ritrovamento.','Il messaggio trasforma il senso di colpa in un tentativo concreto.'],s:'1) Fabula: presentazione dell’aquilone, risata e lite, trasferimento, ritrovamento, messaggio, risposta. Intreccio: ritrovamento → ricordo → decisione → risposta. 2) Il ricordo della risata è analessi. 3) Davide esita tra vergogna e desiderio di riparare. 4) “Quando?” apre alla riconciliazione senza cancellare il passato. 5) Possibile titolo: “Finire l’aquilone”, simbolo di un rapporto lasciato incompleto.'},
 {t:'Epica · confronto strutturato',q:'Confronta Ettore e Odisseo in 12–15 righe: responsabilità, rapporto con la famiglia, qualità eroica e rapporto con il destino. Inserisci almeno un episodio per ciascuno.',level:'SCRITTURA',h:['Ettore: Troia, Andromaca, dovere. Odisseo: Itaca, Penelope, metis e ritorno.','Organizza per criteri, non prima tutto un personaggio e poi tutto l’altro.'],s:'Criteri: tesi iniziale; quattro criteri di confronto; episodi pertinenti; almeno una somiglianza e una differenza esplicite; connettivi; conclusione. Ettore sacrifica il desiderio familiare al dovere verso Troia; Odisseo usa intelligenza e resistenza per tornare alla famiglia. Entrambi difendono casa e identità, ma in forme eroiche diverse.'},
 {t:'Riassunto vincolato',q:'Riassumi “Il quaderno blu” in 55–65 parole, senza discorso diretto e senza giudizi personali.',level:'SCRITTURA',h:['Conserva ritrovamento, ricordo, esitazione, messaggio e risposta.','Trasforma le battute in discorso indiretto.'],s:'Controllo: 55–65 parole; terza persona; ordine chiaro; nessuna citazione diretta; niente dettagli secondari della lista; deve emergere il tentativo di riconciliazione.'},
 {t:'Scrittura argomentativa',q:'Scrivi 18–20 righe: “Chiedere aiuto è un segno di debolezza?”. Inserisci tesi, antitesi, confutazione, esempio e conclusione.',level:'SCRITTURA',h:['Puoi distinguere dipendenza passiva e richiesta consapevole.','Usa: alcuni ritengono…, tuttavia…, per esempio…, dunque….'],s:'Griglia: tesi chiara 2 punti; argomenti 2; antitesi e confutazione 2; esempio pertinente 1; organizzazione e connettivi 1; correttezza 2. Una possibile tesi è che chiedere aiuto, quando nasce dalla consapevolezza dei propri limiti e mira a imparare, richieda responsabilità e coraggio.'},
 {t:'Revisione completa',q:'Riscrivi migliorando coesione e punteggiatura: “Giulia era preoccupata Giulia aveva perso il foglio però Giulia ricordava i dati quindi ha rifatto il lavoro e poi lo consegnava.”',level:'MEDIO',h:['Elimina ripetizioni e separa i nuclei.','Mantieni coerente il tempo verbale.'],s:'“Giulia era preoccupata perché aveva perso il foglio; tuttavia ricordava i dati, quindi rifece il lavoro e poi lo consegnò.”'}
);

// Assegna il nuovo materiale alle giornate senza togliere quello già presente.
const mathStart=exercises.math.length-12, itaStart=exercises.ita.length-12;
dayMaterial[0].mt.push(11); dayMaterial[0].me.push(mathStart,mathStart+1,mathStart+2);
dayMaterial[1].mt.push(12); dayMaterial[1].me.push(mathStart+3,mathStart+5,mathStart+6);
dayMaterial[2].mt.push(12,13); dayMaterial[2].me.push(mathStart+4,mathStart+6,mathStart+7,mathStart+8);
dayMaterial[3].mt.push(13); dayMaterial[3].me.push(mathStart+7,mathStart+10,mathStart+11);
dayMaterial[0].it.push(12); dayMaterial[0].ie.push(itaStart,itaStart+2);
dayMaterial[1].it.push(12); dayMaterial[1].ie.push(itaStart+3,itaStart+4);
dayMaterial[2].it.push(13,14); dayMaterial[2].ie.push(itaStart+5,itaStart+6,itaStart+7);
dayMaterial[3].it.push(13,14); dayMaterial[3].ie.push(itaStart+1,itaStart+8,itaStart+10);
dayMaterial[4].mt.push(11,12,13); dayMaterial[4].it.push(12,13,14);
dayMaterial[5].it.push(12,13,14); dayMaterial[5].ie.push(itaStart+9,itaStart+11);

examSets.mathC={title:'Matematica · Simulazione C',minutes:120,questions:[
 ['Calcolo numerico','Calcola 3/4−[1/2:(−3/2)].','1/2:(−3/2)=−1/3; quindi 3/4+1/3=13/12.'],
 ['Scomposizione','Scomponi 4x³−16x²+16x.','4x(x²−4x+4)=4x(x−2)².'],
 ['Ruffini','Scomponi x³+x²−4x−4.','Raccoglimento parziale o Ruffini: (x+1)(x²−4)=(x+1)(x−2)(x+2).'],
 ['Frazioni algebriche','Semplifica (x²−1)/(x²+2x+1) e indica le C.E.','C.E. x≠−1. Risultato (x−1)/(x+1).'],
 ['Equazione fratta','Risolvi (x+3)/(x−2)=2.','C.E. x≠2. x+3=2x−4 → x=7, ammesso.'],
 ['Disequazione fratta','Risolvi (x−1)/(x+3)<0.','Punti −3 e 1; soluzione −3<x<1.'],
 ['Problema','Il triplo di un numero diminuito di 4 è uguale al numero aumentato di 18. Trovalo.','3x−4=x+18 → 2x=22 → x=11.'],
 ['Geometria','Un triangolo isoscele ha angolo al vertice di 38°. Calcola gli angoli alla base e l’esterno adiacente a uno di essi.','Angoli alla base 71°; esterno 109°.']
]};
examSets.itaA={title:'Italiano · Simulazione A',minutes:90,questions:[
 ['Comprensione e narratologia','Usa il testo “La fermata”: riassumi in 70 parole, indica narratore e focalizzazione, dividi in sequenze e interpreta la firma.','Confronta con la soluzione guidata dell’esercizio; ogni risposta deve includere una prova testuale.'],
 ['Analisi logica','Analizza: “Alla fermata, la madre di Nora consegnò silenziosamente la busta firmata alla figlia.”','Luogo: alla fermata; soggetto: madre; specificazione: di Nora; PV consegnò; modo silenziosamente; oggetto busta; attributo firmata; termine alla figlia.'],
 ['Verbi','Analizza: “Avevano discusso; quando l’autobus comparve, Nora comprese che la madre aveva deciso.”','avevano discusso e aveva deciso: indicativo trapassato prossimo; comparve e comprese: indicativo passato remoto; tutte 3ª singolare, attive.'],
 ['Ortografia e punteggiatura','Correggi: “Nora non sà qual’è la scelta giusta però a deciso di provare.”','“Nora non sa qual è la scelta giusta, però ha deciso di provare.”'],
 ['Scrittura','Scrivi 15 righe: “La fiducia elimina la paura o permette di agire nonostante la paura?”.','Valuta tesi, due argomenti, riferimento al testo, connettivi, conclusione e correttezza.']
]};

const oldExamPage=examPage;
examPage=function(){return oldExamPage().replace('</div><div class="card" style="margin-top:18px">',`<div class="card"><span class="kicker">MATEMATICA C</span><h3>Prova di consolidamento</h3><p class="muted">8 quesiti · livello progressivo · 120 minuti</p><button class="btn orange" onclick="startExam('mathC')">Avvia prova C</button></div><div class="card"><span class="kicker">ITALIANO A</span><h3>Prova guidata completa</h3><p class="muted">Comprensione, grammatica e scrittura · 90 minuti</p><button class="btn" onclick="startExam('itaA')">Avvia Italiano A</button></div></div><div class="card" style="margin-top:18px">`)};

// Una bussola compatta in cima a ogni materia: Filippo sa sempre cosa fare.
const masterySubject=subject;
subject=function(kind){let guide=kind==='math'?'<b>Ordine consigliato:</b> regole e segni → scomposizioni → divisione/Ruffini → frazioni → equazioni → disequazioni → problemi → geometria. Scrivi sempre C.E. e controlli.':'<b>Ordine consigliato:</b> prima comprendi il testo → poi prova ogni risposta → completa grammatica e verbi → scrivi → rileggi in tre passaggi: contenuto, sintassi, ortografia.';return `<div class="card warning"><span class="kicker">BUSSOLA PER LA PROVA</span><p>${guide}</p><p><b>Regola d’oro:</b> prova senza aiuto; apri un indizio; correggi; rifai il giorno dopo senza guardare.</p></div>`+masterySubject(kind)};
render();
